### ISSUE TITLE
Если выбрать пользователя и закрыть окно, всё равно появляется диалог отправки файла

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#16]
![image](https://user-images.githubusercontent.com/12204657/70811078-f7bfc080-1dd5-11ea-9ac8-a675b5f73721.png)

**Comment by AndreyTykhonov** [comment]
#16 дубликат

**Comment by OddMorning** [comment]
У #8 такой интересный заголовок, никогда не догадался бы что дубликат 

![image](https://user-images.githubusercontent.com/12204657/70811765-58033200-1dd7-11ea-9658-9b31b18f07a9.png)
