### ISSUE TITLE
Хранить API для загрузки на своём сервере

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#2]
Программа обращается сначала к своему серверу, получает оттуда ссылки загрузки и уже по ним загружает файл.
Плюсы:
* При смене API не нужно будет пересобирать приложения для компьютера, телефона, веба и рассылать его всем подряд.
* Если программой пользуется человек, который не дружит с техникой, то тебе не нужно объяснять ему как скачать и обновить программу. На компьютере можно сделать автообновление, а если это телефон?
* В теории, с таким походом можно хранить файлы на любом файлообменнике. Не то, чтобы это было нужно, но мало ли.

**Comment by AndreyTykhonov** [comment]
Учитывая что в теории будет скорее всего 2 сервера, то врятли нужно!
