### ISSUE TITLE
Если нажать «назад» в окне добавления пользователя, то добавляется пустой

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#22]
![image](https://user-images.githubusercontent.com/12204657/70847348-d3ff8780-1e74-11ea-88e0-627fd7df46ac.png)

**Comment by AndreyTykhonov** [comment]
Может вообще сделать кнопку ДОБАВИТЬ в добавлении?7 И чтобы назад выходило а не добавляло, а то сложная фича
