### ISSUE TITLE
Пользователь сам решает, куда принимать файлы

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#3]
Если ты Вася, и у тебя есть компьютер и телефон, то ты можешь выбрать компьютер своим основным устройством. Когда кто-то другой хочет отправить файл и выбирает из контактов «Вася», то файл приходит на компьютер. А если компьютер отключен, то либо на все остальные, либо на какое-то конкретное устройство приходит уведомление: «Дима отправил файл, но на данный момент устройство “компьютер” недоступно» и под ним кнопки «Перенаправить файл сюда» (скачивает на телефон и файл считается принятым), «Скачать копию» (файл скачается, но когда компьютер будет в сети, то файл на него всё равно примется) и «Скрыть» (не знаю, много ли толка от такой кнопки, ведь уведомления можно закрыть и без каких-либо кнопок).

Так же Вася может в настройках аккаунта сделать выбранные устройства видимыми, поэтому другой пользователь может отправить файл либо «Васе» (сработает как описано выше), либо на «Вася/Телефон» (файл отправится прямиком на телефон, игнорируя настройку предпочитаемого устройства)

**Comment by AndreyTykhonov** [comment]
Как-то очень комплексно, и вряд ли использоваться будет часто
Всякие картинки и прочие мелкие файлы явно проще отправить через телегу / дискорд
А большие файлы на телефоне вряд ли нужны, причем они могут быть под платформу
Плюс Вася может не хотеть палить свои устройства, слишком много доступа
Да и проще дать айди телефона если очень нужно

**Comment by OddMorning** [comment]
Вспомнил, зачем это нужно было. Когда человек знает что делает, то всё в порядке, а вот если человек вообще не знаком с пэкой или он просто не хочет заморачиваться? Я мог бы скидывать маме на телефон песни в папку с музыкой, если она попросит что-нибудь скачать и обрезать новое для звука звонка. Хотя нет, тут уже нужно что-нибудь вроде тима, чтобы можно было не только передавать, но ещё и переименовывать файлы и делать прочие манипуляции, которые в концепцию программы для передачи файлов уже не входят

**Comment by AndreyTykhonov** [comment]
Это ещё актуально? Кажется с айди все просто и прозрачно. Нужно на телефон - кинул айди телнфона

**Comment by OddMorning** [comment]
Ого, этому тикету в среду стукнул год. Вроде бы он писался с учётом аккаунтов, но поскольку у нас только айди, то и тикет становится неактуален
