### ISSUE TITLE
Не работает редактирование пользователей

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#30]
По долгому тапу по пользователю предлагает либо удалить, либо редактировать. Удаление не работает, а редактирование иногда показывает айди 0, а иногда тоже просто ничего не делает

**Comment by AndreyTykhonov** [comment]
Нужно больше инфы, может это #18 ?

**Comment by OddMorning** [comment]
В #18 упоминаются файлы, а тут список пользователей. И я понял, в чём дело. Нужно сначала нажать на пользователя, чтобы он стал оранжевым, и только после этого зажать его. Только тогда будут работать удаление и редактирование.

Предлагаю автовыделять пользователя по зажатию

**Comment by AndreyTykhonov** [comment]
Так падажите, файлы зажимать нельзя же, то дубликат!1 #18

**Comment by OddMorning** [comment]
Ты под файлов подразумеваешь пункт листвиева что ли? Потому что с файлами вообще никакие операции производить нельзя, хоть зажимай, хоть не зажимай

**Comment by AndreyTykhonov** [comment]
Я когад писал то ошибся
