### ISSUE TITLE
Не сохраняются пользователи после редактирования

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#33]
Я вбил твой ID с ошибкой. Отредактировать смог, и оно работает, но когда выхожу из программы и захожу обратно, то он снова старый. Но если после этого добавить ещё юзера, то норм. Видимо, по событию редактирования данные не отсылаются на сервер

**Comment by AndreyTykhonov** [comment]
На пекарне тоже самое

**Comment by OddMorning** [comment]
Код настолько кроссплатформенный, что на обеих платформах не привязаны одинаковые события?)

**Comment by AndreyTykhonov** [comment]
Там все сложнее. Формы взаимодействуют с моделью, а модель сохраняется при редактировании, но похоже редактирование срабатывает только при добавлении / удалении
