### ISSUE TITLE
Автоматические добавление своего контакта

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#37]
Хм, а это баг или ~~оставшаяся с тестов~~ фича?

![image](https://user-images.githubusercontent.com/12204657/71062217-07932800-217b-11ea-9692-8846f133b631.png)

![image](https://user-images.githubusercontent.com/12204657/71062243-15e14400-217b-11ea-93c4-1da63de6606a.png)

UPD: Я сам себе файлы не отправлял

**Comment by AndreyTykhonov** [comment]
То есть ты себе не друг????

**Comment by OddMorning** [comment]
Нет, не друг!1
Но смущает то, что это появляется не при первом запуске, а только при втором (либо после каких-то манипуляций, которые я успел сделать)
