### ISSUE TITLE
Концепты дизайнов только для вам

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#40]
Хотел сделать редизайн загрузок, но потом что-то понесло. Если вдруг что, местами может встречаться ад перфекциониста, так как я не думал что меня затянет настолько серьёзно и ставил объекты на глаз

# Главное окно
* Перекрасить тема с синего на зелёный, так как ФФС всегда был зелёным ~~(забудем тот серый интерфейс с не-зелёным камуфляжным логотипом)~~;
* Кнопки с выезжающим меню больше нет, вместо неё стильный модный молодёжный дизайн, который не знаю насколько модный, просто из головы придумал что-то и оно мне вдруг даже понравилось;
* Во время загрузки показывается процент, а когда файл загружен/скачен, то отображается его дата;
* Цвет прогрессбара синий при скачивании, оранжевый при отправке и зелёный в спокойствии;
* Если у тебя есть возможность отображать размер файла (всегда отображать только три цифры), как делает винда, то было бы просто идеально. То есть `1.13 KB`, `47.3 KB`, `640 KB`;
* Тап по файлу открывает файл;
* Тап по своему айди скопирует его в буфер (не уверен в надобности, но а вдруг);
* Тап по «Send file» открывает список контактов.

### Основной вариант
![image](https://user-images.githubusercontent.com/12204657/71160569-dee16000-2258-11ea-98e3-c5dbc84c7563.png)

### Вариант, если в будущем у программы настройки не появятся )0
![image](https://user-images.githubusercontent.com/12204657/71160576-e274e700-2258-11ea-8cd0-f4a27348a92d.png)

### Первоначальный вариант, но что-то он мне показался не очень
![image](https://user-images.githubusercontent.com/12204657/71160580-e6086e00-2258-11ea-9915-a410a60c1bb5.png)

# Контакты
* Тап по контакту открывает отправку файлов;
* Долгий тап по контакту открывает его редактирование.

### С закосом под стоковое приложение контактов
![image](https://user-images.githubusercontent.com/12204657/71157574-4c8a8d80-2253-11ea-896b-56f0419b5705.png)

### Альтернативный вариант, но что-то мне в нём всё равно не нравится
![image](https://user-images.githubusercontent.com/12204657/71157582-51e7d800-2253-11ea-9c31-46adefbd22ca.png)

# Редактирование/создание контакта
* [Back] уйдёт без сохранения изменений;
* [Save] сохранит изменения;
* Вне контекста звучит глупо, но оно интуитивнее чем принудительное добавление по выходу, как оно есть сейчас… вроде как.

![image](https://user-images.githubusercontent.com/12204657/71158444-046c6a80-2255-11ea-815c-023517368421.png)

**Comment by AndreyTykhonov** [comment]
![image](https://user-images.githubusercontent.com/49648460/71159845-219e3a80-224f-11ea-9372-8d3ddf215444.png)

**Comment by AndreyTykhonov** [comment]
А можно всякие цвета, файлы картинок?7

**Comment by OddMorning** [comment]
# Общее
Цвет темы: `#4caf50`
Иконка настроек: ![settings](https://user-images.githubusercontent.com/12204657/71161496-80b57c80-225a-11ea-8a85-b1af72b19d34.png)
Стрелки влево и вправо: ![arrow-left](https://user-images.githubusercontent.com/12204657/71161516-8b701180-225a-11ea-91b9-b89ad7bfb40f.png) ![arrow-right](https://user-images.githubusercontent.com/12204657/71161521-8d39d500-225a-11ea-9983-6c0332e07019.png)
(Они белого цвета, но они тут есть, фотошопом клянусь)

# Загрузки
## Download
`#1e88e5`
![download](https://user-images.githubusercontent.com/12204657/71161204-fa993600-2259-11ea-9550-a6d30786633c.png) 

## Upload
 `#f57f17`
![upload](https://user-images.githubusercontent.com/12204657/71161202-fa993600-2259-11ea-96f6-fe63588a07e8.png)


# Контакты
Цвет кнопки «добавить новый контакт»: `#2e7d32`

## Добавить новый контакт
![add-new-contant](https://user-images.githubusercontent.com/12204657/71162112-ab540500-225b-11ea-81b2-a4e7fa7cc0e2.png)

## В сети
![contant-online](https://user-images.githubusercontent.com/12204657/71162122-b1e27c80-225b-11ea-9cd3-4a25d9e4a6e4.png)

## Не в сети
![contant](https://user-images.githubusercontent.com/12204657/71162134-b7d85d80-225b-11ea-8090-5677aa0830f0.png)

# Добавление редактирование контакта

## Имя (обычное и в фокусе)
![name-blur](https://user-images.githubusercontent.com/12204657/71162375-287f7a00-225c-11ea-81e6-231915737665.png) ![name-focus](https://user-images.githubusercontent.com/12204657/71162379-2a493d80-225c-11ea-9ee5-8e8f37e780e9.png)

## ID (обычный и в фокусе)
![id-blur](https://user-images.githubusercontent.com/12204657/71162396-3503d280-225c-11ea-8c28-223972594666.png) ![id-focus](https://user-images.githubusercontent.com/12204657/71162407-37662c80-225c-11ea-9470-1d78d6aabd18.png)

# P.S.
~~А векторы можно было бы красить прямо в коде~~

**Comment by AndreyTykhonov** [comment]
А векторы есть их?7

**Comment by OddMorning** [comment]
Мог бы сразу сказать, что ты могёшь в векторы, я бы не мучался нарезанием пнгшек.
Может позже, сейчас уже некогда

**Comment by AndreyTykhonov** [comment]
[svg.zip](https://github.com/AndreyTykhonov/FastFileSend/files/3982822/svg.zip)

**Comment by AndreyTykhonov** [comment]
В дизайне нет бокового меню, и нет возможности нажать на список контактов, кроме как через отправку файлов (фича?)
Похоже, что дефолтный тулбар ограчниен, и выглядят его возможности примерно так:
![image](https://user-images.githubusercontent.com/49648460/79837546-48fe4300-83ba-11ea-819f-a15d0a8d9156.png)
(Кнопка меню, название, справа стакаются кастомные кнопки, можно в подпункт ... вынести)

**Comment by OddMorning** [comment]
А ты много видел современных приложений с этим тулбаром? Я у себя просмотрел всё что было, в исходном виде оно было только у стима и слегка модифицированном у 4pda. Может быть тогда вообще пересмотреть дизайн, раз тулбар уже нигде не используется?

**Comment by AndreyTykhonov** [comment]
Я решил пройтись по гугловским программам (и не только)

![image](https://user-images.githubusercontent.com/49648460/79838064-1e60ba00-83bb-11ea-8336-770786476528.png)
![image](https://user-images.githubusercontent.com/49648460/79838085-2587c800-83bb-11ea-8e5d-a3ffcf52e71a.png)
![image](https://user-images.githubusercontent.com/49648460/79838104-2caed600-83bb-11ea-8b72-629f4c01aacd.png)
![image](https://user-images.githubusercontent.com/49648460/79838120-32a4b700-83bb-11ea-91d5-2ee27ad2ca80.png)
![image](https://user-images.githubusercontent.com/49648460/79838132-36d0d480-83bb-11ea-8518-99c856485060.png)

В целом он у них используется. Но в гугл картах, почте и календаре какой-то другой вариант тулбокса, либо они везде свои костыли закидали, либо это какой-то новый стоковый компонент

**Comment by OddMorning** [comment]
Значит это как-то мне повезло, что во всех программах вместо тублара была строка поиска

**Comment by AndreyTykhonov** [comment]
![image](https://user-images.githubusercontent.com/49648460/79838304-75668f00-83bb-11ea-8416-537554bae774.png)

**Comment by OddMorning** [comment]
Раз есть #89, то #40, наверное, уже и не нужен
