### ISSUE TITLE
Тихий выход при первом запуске

### ISSUE THREAD

**Issue by OddMorning** [AndreyTykhonov/FastFileSend#61]
При первом запуске появляется окошко «разрешить доступ к FS?», но позади этого окошка программа просто закрывается, не оставляя логов

**Comment by AndreyTykhonov** [comment]
По всей видимости, права не выдаются без перезапуска проги

https://github.com/AndreyTykhonov/FastFileSend/blob/master/FastFileSend/FastFileSend.Android/MainActivity.cs#L46
